"""Update Test and TestAttempt logic

Revision ID: 36c334da46bd
Revises: bd7695eec92f
Create Date: 2025-12-29 11:03:38.809717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c334da46bd'
down_revision: Union[str, None] = 'bd7695eec92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_passages',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Enum('reading_passage', 'listening_audio', 'speaking_cue_card', name='content_type'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', 
            postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', 
                            name='difficulty_level', create_type=False), 
            nullable=True
        ),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', 
            postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', 
                            name='content_status', create_type=False), 
            nullable=False
        ),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_attempts_student_id', 'test_attempts', ['student_id'], unique=False)
    op.create_index('idx_test_attempts_test_id_status', 'test_attempts', ['test_id', 'status'], unique=False)
    op.add_column('test_questions', sa.Column('group_order_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'test_questions', ['group_id', 'group_order_number'])
    op.add_column('test_responses', sa.Column('rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('test_responses', sa.Column('band_score', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('test_responses', sa.Column('ai_points_earned', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('test_responses', sa.Column('ai_band_score', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('test_responses', sa.Column('ai_rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('test_responses', sa.Column('teacher_points_earned', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('test_responses', sa.Column('teacher_band_score', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('test_responses', sa.Column('teacher_rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('test_responses', 'points_earned',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_test_responses_attempt_id', 'test_responses', ['attempt_id'], unique=False)
    op.drop_column('test_responses', 'ai_score')
    op.drop_column('test_responses', 'teacher_score')
    op.drop_column('test_responses', 'feedback')
    op.add_column('test_section_parts', sa.Column('passage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'test_section_parts', 'content_passages', ['passage_id'], ['id'])
    op.drop_column('test_section_parts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_section_parts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_section_parts', type_='foreignkey')
    op.drop_column('test_section_parts', 'passage_id')
    op.add_column('test_responses', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('test_responses', sa.Column('teacher_score', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('test_responses', sa.Column('ai_score', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.drop_index('idx_test_responses_attempt_id', table_name='test_responses')
    op.alter_column('test_responses', 'points_earned',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('test_responses', 'teacher_rubric_scores')
    op.drop_column('test_responses', 'teacher_band_score')
    op.drop_column('test_responses', 'teacher_points_earned')
    op.drop_column('test_responses', 'ai_rubric_scores')
    op.drop_column('test_responses', 'ai_band_score')
    op.drop_column('test_responses', 'ai_points_earned')
    op.drop_column('test_responses', 'band_score')
    op.drop_column('test_responses', 'rubric_scores')
    op.drop_constraint(None, 'test_questions', type_='unique')
    op.drop_column('test_questions', 'group_order_number')
    op.drop_index('idx_test_attempts_test_id_status', table_name='test_attempts')
    op.drop_index('idx_test_attempts_student_id', table_name='test_attempts')
    op.drop_table('content_passages')
    # ### end Alembic commands ###
