"""Add assessment and grading system tables

Revision ID: 47a16127fe21
Revises: 20ab55522d8b
Create Date: 2025-11-02 00:47:26.597851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a16127fe21'
down_revision: Union[str, None] = '20ab55522d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attendance_date', table_name='attendance_records')
    op.drop_index('idx_attendance_session_status', table_name='attendance_records')
    op.drop_index('idx_attendance_status', table_name='attendance_records')
    op.drop_index('idx_attendance_student', table_name='attendance_records')
    op.drop_index('idx_attendance_student_date', table_name='attendance_records')
    op.drop_index('idx_attendance_unique', table_name='attendance_records')
    op.drop_index('idx_class_sessions_class_id', table_name='class_sessions')
    op.drop_index('idx_class_sessions_date', table_name='class_sessions')
    op.drop_index('idx_class_sessions_room', table_name='class_sessions')
    op.drop_index('idx_class_sessions_status', table_name='class_sessions')
    op.drop_index('idx_class_sessions_teacher', table_name='class_sessions')
    op.drop_index('idx_room_schedule_conflict', table_name='class_sessions', postgresql_where="((status <> ALL (ARRAY['cancelled'::session_status, 'postponed'::session_status])) AND (room_id IS NOT NULL))")
    op.drop_index('idx_teacher_schedule_conflict', table_name='class_sessions', postgresql_where="(status <> ALL (ARRAY['cancelled'::session_status, 'postponed'::session_status]))")
    op.drop_constraint('fk_c_created_by', 'classes', type_='foreignkey')
    op.add_column('question_bank', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('question_bank', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.drop_index('idx_questions_difficulty', table_name='question_bank')
    op.drop_index('idx_questions_level', table_name='question_bank')
    op.drop_index('idx_questions_search', table_name='question_bank', postgresql_using='gin')
    op.drop_index('idx_questions_skill', table_name='question_bank')
    op.drop_index('idx_questions_status', table_name='question_bank')
    op.drop_index('idx_questions_tags', table_name='question_bank', postgresql_using='gin')
    op.drop_index('idx_questions_type', table_name='question_bank')
    op.create_foreign_key(None, 'question_bank', 'users', ['updated_by'], ['id'])
    op.add_column('test_attempts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('test_attempts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_attempts', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('test_attempts', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('test_attempts', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index('idx_test_attempts_status', table_name='test_attempts')
    op.drop_index('idx_test_attempts_student', table_name='test_attempts')
    op.drop_index('idx_test_attempts_student_submitted', table_name='test_attempts')
    op.drop_index('idx_test_attempts_submitted', table_name='test_attempts')
    op.drop_index('idx_test_attempts_test', table_name='test_attempts')
    op.drop_index('idx_test_attempts_test_status', table_name='test_attempts')
    op.drop_index('idx_test_attempts_unique', table_name='test_attempts')
    op.create_unique_constraint('uq_test_student_attempt', 'test_attempts', ['test_id', 'student_id', 'attempt_number'])
    op.create_foreign_key(None, 'test_attempts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'test_attempts', 'users', ['created_by'], ['id'])
    op.add_column('test_questions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('test_questions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_questions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('test_questions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.drop_index('idx_test_questions_order', table_name='test_questions')
    op.drop_index('idx_test_questions_test', table_name='test_questions')
    op.drop_index('idx_test_questions_unique', table_name='test_questions')
    op.create_unique_constraint('uq_test_question', 'test_questions', ['test_id', 'question_id'])
    op.create_foreign_key(None, 'test_questions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'test_questions', 'users', ['updated_by'], ['id'])
    op.add_column('test_responses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_responses', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('test_responses', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.drop_index('idx_test_responses_attempt', table_name='test_responses')
    op.drop_index('idx_test_responses_flagged', table_name='test_responses')
    op.drop_index('idx_test_responses_question', table_name='test_responses')
    op.drop_index('idx_test_responses_unique', table_name='test_responses')
    op.create_foreign_key(None, 'test_responses', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'test_responses', 'users', ['updated_by'], ['id'])
    op.add_column('tests', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.drop_index('idx_tests_class', table_name='tests')
    op.drop_index('idx_tests_course', table_name='tests')
    op.drop_index('idx_tests_creator', table_name='tests')
    op.drop_index('idx_tests_status', table_name='tests')
    op.drop_index('idx_tests_time_window', table_name='tests')
    op.drop_index('idx_tests_type', table_name='tests')
    op.create_foreign_key(None, 'tests', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_index('idx_tests_type', 'tests', ['test_type'], unique=False)
    op.create_index('idx_tests_time_window', 'tests', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_tests_status', 'tests', ['status'], unique=False)
    op.create_index('idx_tests_creator', 'tests', ['created_by'], unique=False)
    op.create_index('idx_tests_course', 'tests', ['course_id'], unique=False)
    op.create_index('idx_tests_class', 'tests', ['class_id'], unique=False)
    op.drop_column('tests', 'updated_by')
    op.drop_column('tests', 'deleted_at')
    op.drop_constraint(None, 'test_responses', type_='foreignkey')
    op.drop_constraint(None, 'test_responses', type_='foreignkey')
    op.create_index('idx_test_responses_unique', 'test_responses', ['attempt_id', 'question_id'], unique=True)
    op.create_index('idx_test_responses_question', 'test_responses', ['question_id'], unique=False)
    op.create_index('idx_test_responses_flagged', 'test_responses', ['flagged_for_review'], unique=False)
    op.create_index('idx_test_responses_attempt', 'test_responses', ['attempt_id'], unique=False)
    op.drop_column('test_responses', 'updated_by')
    op.drop_column('test_responses', 'created_by')
    op.drop_column('test_responses', 'deleted_at')
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_constraint('uq_test_question', 'test_questions', type_='unique')
    op.create_index('idx_test_questions_unique', 'test_questions', ['test_id', 'question_id'], unique=True)
    op.create_index('idx_test_questions_test', 'test_questions', ['test_id'], unique=False)
    op.create_index('idx_test_questions_order', 'test_questions', ['test_id', 'order_number'], unique=True)
    op.drop_column('test_questions', 'updated_by')
    op.drop_column('test_questions', 'created_by')
    op.drop_column('test_questions', 'deleted_at')
    op.drop_column('test_questions', 'updated_at')
    op.drop_constraint(None, 'test_attempts', type_='foreignkey')
    op.drop_constraint(None, 'test_attempts', type_='foreignkey')
    op.drop_constraint('uq_test_student_attempt', 'test_attempts', type_='unique')
    op.create_index('idx_test_attempts_unique', 'test_attempts', ['test_id', 'student_id', 'attempt_number'], unique=True)
    op.create_index('idx_test_attempts_test_status', 'test_attempts', ['test_id', 'status'], unique=False)
    op.create_index('idx_test_attempts_test', 'test_attempts', ['test_id'], unique=False)
    op.create_index('idx_test_attempts_submitted', 'test_attempts', ['submitted_at'], unique=False)
    op.create_index('idx_test_attempts_student_submitted', 'test_attempts', ['student_id', 'submitted_at'], unique=False)
    op.create_index('idx_test_attempts_student', 'test_attempts', ['student_id'], unique=False)
    op.create_index('idx_test_attempts_status', 'test_attempts', ['status'], unique=False)
    op.alter_column('test_attempts', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_column('test_attempts', 'updated_by')
    op.drop_column('test_attempts', 'created_by')
    op.drop_column('test_attempts', 'deleted_at')
    op.drop_column('test_attempts', 'updated_at')
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.create_index('idx_questions_type', 'question_bank', ['question_type'], unique=False)
    op.create_index('idx_questions_tags', 'question_bank', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_questions_status', 'question_bank', ['status'], unique=False)
    op.create_index('idx_questions_skill', 'question_bank', ['skill_area'], unique=False)
    op.create_index('idx_questions_search', 'question_bank', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || question_text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_questions_level', 'question_bank', ['course_level'], unique=False)
    op.create_index('idx_questions_difficulty', 'question_bank', ['difficulty_level'], unique=False)
    op.drop_column('question_bank', 'updated_by')
    op.drop_column('question_bank', 'deleted_at')
    op.create_foreign_key('fk_c_created_by', 'classes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index('idx_teacher_schedule_conflict', 'class_sessions', ['teacher_id', 'session_date', 'start_time', 'end_time'], unique=True, postgresql_where="(status <> ALL (ARRAY['cancelled'::session_status, 'postponed'::session_status]))")
    op.create_index('idx_room_schedule_conflict', 'class_sessions', ['room_id', 'session_date', 'start_time', 'end_time'], unique=True, postgresql_where="((status <> ALL (ARRAY['cancelled'::session_status, 'postponed'::session_status])) AND (room_id IS NOT NULL))")
    op.create_index('idx_class_sessions_teacher', 'class_sessions', ['teacher_id'], unique=False)
    op.create_index('idx_class_sessions_status', 'class_sessions', ['status'], unique=False)
    op.create_index('idx_class_sessions_room', 'class_sessions', ['room_id'], unique=False)
    op.create_index('idx_class_sessions_date', 'class_sessions', ['session_date'], unique=False)
    op.create_index('idx_class_sessions_class_id', 'class_sessions', ['class_id'], unique=False)
    op.create_index('idx_attendance_unique', 'attendance_records', ['session_id', 'student_id'], unique=True)
    op.create_index('idx_attendance_student_date', 'attendance_records', ['student_id', 'created_at'], unique=False)
    op.create_index('idx_attendance_student', 'attendance_records', ['student_id'], unique=False)
    op.create_index('idx_attendance_status', 'attendance_records', ['status'], unique=False)
    op.create_index('idx_attendance_session_status', 'attendance_records', ['session_id', 'status'], unique=False)
    op.create_index('idx_attendance_date', 'attendance_records', ['created_at'], unique=False)
    # ### end Alembic commands ###
