"""Message

Revision ID: 642627ddfece
Revises: ba3439530cb9
Create Date: 2025-11-24 16:52:13.772143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642627ddfece'
down_revision: Union[str, None] = 'ba3439530cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('room_type', postgresql.ENUM('direct', 'group', 'class', 'system', 'announcement', name='message_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'room_type')
    # ### end Alembic commands ###
