"""Sync File and Message

Revision ID: 70e89c052097
Revises: 47a16127fe21
Create Date: 2025-11-07 04:04:26.379398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e89c052097'
down_revision: Union[str, None] = '47a16127fe21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_uploads_associated', table_name='file_uploads')
    op.drop_index('idx_file_uploads_created', table_name='file_uploads')
    op.drop_index('idx_file_uploads_hash', table_name='file_uploads')
    op.drop_index('idx_file_uploads_type', table_name='file_uploads')
    op.drop_index('idx_file_uploads_uploader', table_name='file_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_file_uploads_uploader', 'file_uploads', ['uploaded_by'], unique=False)
    op.create_index('idx_file_uploads_type', 'file_uploads', ['upload_type'], unique=False)
    op.create_index('idx_file_uploads_hash', 'file_uploads', ['file_hash'], unique=False)
    op.create_index('idx_file_uploads_created', 'file_uploads', ['created_at'], unique=False)
    op.create_index('idx_file_uploads_associated', 'file_uploads', ['associated_id'], unique=False)
    # ### end Alembic commands ###
