"""add_kpi_module_tables

Revision ID: 762f0df642be
Revises: 7c5efc05bf8c
Create Date: 2026-04-05 19:28:58.684651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '762f0df642be'
down_revision: Union[str, None] = '7c5efc05bf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_calculation_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='job_status_enum'), nullable=True),
    sa.Column('total_teachers', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('kpi_criterias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria_code', sa.String(length=50), nullable=False),
    sa.Column('criteria_name', sa.String(length=100), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='kpi_criteria_status_enum'), nullable=True),
    sa.CheckConstraint('weight_percent > 0', name='check_weight_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria_code')
    )
    op.create_table('kpi_raw_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=False),
    sa.Column('metric_data', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'period', 'source_module', name='uix_kpi_raw_sync')
    )
    op.create_table('kpi_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_name', sa.String(length=20), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reward_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reward_per_lesson', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='kpi_tier_status_enum'), nullable=True),
    sa.CheckConstraint('max_score <= 100', name='check_max_score_limit'),
    sa.CheckConstraint('min_score < max_score', name='check_min_less_than_max'),
    sa.CheckConstraint('min_score >= 0', name='check_min_score_positive'),
    sa.CheckConstraint('reward_per_lesson >= 0', name='check_reward_per_lesson'),
    sa.CheckConstraint('reward_percentage >= 0', name='check_reward_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payroll_run_status_enum'), nullable=True),
    sa.Column('total_processed', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period')
    )
    op.create_table('salaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('contract_type', sa.Enum('FULL_TIME', 'PART_TIME', 'NATIVE', name='salary_contract_type_enum'), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=True),
    sa.Column('base_salary_calc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kpi_bonus_calc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fixed_allowance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_adjustments', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='salary_status_enum'), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('base_salary_calc >= 0', name='check_base_salary_calc'),
    sa.CheckConstraint('kpi_bonus_calc >= 0', name='check_kpi_bonus_calc'),
    sa.CheckConstraint('lesson_count >= 0', name='check_lesson_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'period', name='uix_teacher_salary_period')
    )
    op.create_table('teacher_payroll_configs',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.Enum('FULL_TIME', 'PART_TIME', 'NATIVE', name='payroll_config_contract_type_enum'), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lesson_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_kpi_bonus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fixed_allowance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('base_salary >= 0', name='check_base_salary'),
    sa.CheckConstraint('lesson_rate >= 0', name='check_lesson_rate'),
    sa.CheckConstraint('max_kpi_bonus >= 0', name='check_max_kpi_bonus'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('salary_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salary_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('ALLOWANCE', 'DEDUCTION', name='adjustment_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_adjustment_amount_positive'),
    sa.ForeignKeyConstraint(['salary_id'], ['salaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_monthly_kpis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('kpi_tier_id', sa.Integer(), nullable=True),
    sa.Column('kpi_details', sa.JSON(), nullable=False),
    sa.Column('calculated_bonus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_score >= 0 AND total_score <= 100', name='check_total_score'),
    sa.ForeignKeyConstraint(['kpi_tier_id'], ['kpi_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'period', name='uix_teacher_period')
    )
    op.create_table('kpi_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'REJECTED', name='dispute_status_enum'), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['teacher_monthly_kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_disputes')
    op.drop_table('teacher_monthly_kpis')
    op.drop_table('salary_adjustments')
    op.drop_table('teacher_payroll_configs')
    op.drop_table('salaries')
    op.drop_table('payroll_runs')
    op.drop_table('kpi_tiers')
    op.drop_table('kpi_raw_metrics')
    op.drop_table('kpi_criterias')
    op.drop_table('kpi_calculation_jobs')
    # ### end Alembic commands ###
