"""Minor bug fix

Revision ID: 7c5efc05bf8c
Revises: 36c334da46bd
Create Date: 2025-12-31 17:20:20.693044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5efc05bf8c'
down_revision: Union[str, None] = '36c334da46bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_passages', 'difficulty_level',
               existing_type=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               type_=sa.Enum('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level', native_enum=False),
               existing_nullable=True)
    op.alter_column('content_passages', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               type_=sa.Enum('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('question_bank', 'question_type',
               existing_type=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               type_=sa.Enum('multiple_choice', 'true_false_not_given', 'yes_no_not_given', 'matching_headings', 'matching_information', 'matching_features', 'sentence_completion', 'summary_completion', 'note_completion', 'short_answer', 'diagram_labeling', 'writing_task_1', 'writing_task_2', 'speaking_part_1', 'speaking_part_2', 'speaking_part_3', name='question_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('question_bank', 'skill_area',
               existing_type=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'),
               type_=sa.Enum('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area', native_enum=False),
               existing_nullable=False)
    op.alter_column('question_bank', 'difficulty_level',
               existing_type=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               type_=sa.Enum('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level', native_enum=False),
               existing_nullable=True)
    op.alter_column('question_bank', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               type_=sa.Enum('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::content_status"))
    op.alter_column('question_groups', 'question_type',
               existing_type=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               type_=sa.Enum('multiple_choice', 'true_false_not_given', 'yes_no_not_given', 'matching_headings', 'matching_information', 'matching_features', 'sentence_completion', 'summary_completion', 'note_completion', 'short_answer', 'diagram_labeling', 'writing_task_1', 'writing_task_2', 'speaking_part_1', 'speaking_part_2', 'speaking_part_3', name='question_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('test_attempts', 'status',
               existing_type=postgresql.ENUM('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status'),
               type_=sa.Enum('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::attempt_status"))
    op.alter_column('test_sections', 'skill_area',
               existing_type=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'),
               type_=sa.Enum('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area', native_enum=False),
               existing_nullable=False)
    op.alter_column('tests', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'active', 'closed', 'archived', name='test_status'),
               type_=sa.Enum('draft', 'published', 'active', 'closed', 'archived', name='test_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::test_status"))
    op.alter_column('tests', 'test_type',
               existing_type=postgresql.ENUM('quiz', 'midterm', 'final', 'placement', 'ielts_full', 'ielts_practice', 'homework', 'assessment', name='test_type'),
               type_=sa.Enum('quiz', 'midterm', 'final', 'placement', 'homework', 'assessment', name='test_type', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'test_type',
               existing_type=sa.Enum('quiz', 'midterm', 'final', 'placement', 'homework', 'assessment', name='test_type', native_enum=False),
               type_=postgresql.ENUM('quiz', 'midterm', 'final', 'placement', 'ielts_full', 'ielts_practice', 'homework', 'assessment', name='test_type'),
               existing_nullable=True)
    op.alter_column('tests', 'status',
               existing_type=sa.Enum('draft', 'published', 'active', 'closed', 'archived', name='test_status', native_enum=False),
               type_=postgresql.ENUM('draft', 'published', 'active', 'closed', 'archived', name='test_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::test_status"))
    op.alter_column('test_sections', 'skill_area',
               existing_type=sa.Enum('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area', native_enum=False),
               type_=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'),
               existing_nullable=False)
    op.alter_column('test_attempts', 'status',
               existing_type=sa.Enum('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status', native_enum=False),
               type_=postgresql.ENUM('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::attempt_status"))
    op.alter_column('question_groups', 'question_type',
               existing_type=sa.Enum('multiple_choice', 'true_false_not_given', 'yes_no_not_given', 'matching_headings', 'matching_information', 'matching_features', 'sentence_completion', 'summary_completion', 'note_completion', 'short_answer', 'diagram_labeling', 'writing_task_1', 'writing_task_2', 'speaking_part_1', 'speaking_part_2', 'speaking_part_3', name='question_type', native_enum=False),
               type_=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               existing_nullable=False)
    op.alter_column('question_bank', 'status',
               existing_type=sa.Enum('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status', native_enum=False),
               type_=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::content_status"))
    op.alter_column('question_bank', 'difficulty_level',
               existing_type=sa.Enum('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level', native_enum=False),
               type_=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               existing_nullable=True)
    op.alter_column('question_bank', 'skill_area',
               existing_type=sa.Enum('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area', native_enum=False),
               type_=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'),
               existing_nullable=False)
    op.alter_column('question_bank', 'question_type',
               existing_type=sa.Enum('multiple_choice', 'true_false_not_given', 'yes_no_not_given', 'matching_headings', 'matching_information', 'matching_features', 'sentence_completion', 'summary_completion', 'note_completion', 'short_answer', 'diagram_labeling', 'writing_task_1', 'writing_task_2', 'speaking_part_1', 'speaking_part_2', 'speaking_part_3', name='question_type', native_enum=False),
               type_=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               existing_nullable=False)
    op.alter_column('content_passages', 'status',
               existing_type=sa.Enum('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status', native_enum=False),
               type_=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               existing_nullable=False)
    op.alter_column('content_passages', 'difficulty_level',
               existing_type=sa.Enum('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level', native_enum=False),
               type_=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               existing_nullable=True)
    # ### end Alembic commands ###
