"""Create group chat

Revision ID: 8cb13ac9bcda
Revises: 642627ddfece
Create Date: 2025-11-26 00:19:49.831912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb13ac9bcda'
down_revision: Union[str, None] = '642627ddfece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'moderator', 'member', name='member_role', native_enum=False), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_room_id', 'user_id', name='uq_room_member')
    )
    op.create_index('ix_room_members_room', 'chat_room_members', ['chat_room_id'], unique=False)
    op.create_index('ix_room_members_user', 'chat_room_members', ['user_id'], unique=False)
    op.add_column('chat_rooms', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('chat_rooms', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('chat_rooms', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('chat_rooms', 'room_type',
               existing_type=postgresql.ENUM('direct', 'group', 'class', 'system', 'announcement', name='message_type'),
               type_=sa.Enum('direct', 'group', 'class', 'system', 'announcement', name='message_type', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key(None, 'chat_rooms', 'users', ['created_by'], ['id'])
    op.alter_column('message_recipients', 'recipient_type',
               existing_type=postgresql.ENUM('user', 'class', 'role', name='recipient_type'),
               type_=sa.Enum('user', 'group', 'class', name='recipient_type', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'user'::recipient_type"))
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('direct', 'group', 'class', 'system', 'announcement', name='message_type'),
               type_=sa.Enum('direct', 'group', 'class', 'system', 'announcement', name='message_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'direct'::message_type"))
    op.alter_column('messages', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='message_priority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', name='message_priority', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'normal'::message_priority"))
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'failed', 'cancelled', name='message_status'),
               type_=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'failed', 'cancelled', name='message_status', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'sent'::message_status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'status',
               existing_type=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'failed', 'cancelled', name='message_status', native_enum=False),
               type_=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'failed', 'cancelled', name='message_status'),
               nullable=True,
               existing_server_default=sa.text("'sent'::message_status"))
    op.alter_column('messages', 'priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', name='message_priority', native_enum=False),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='message_priority'),
               nullable=True,
               existing_server_default=sa.text("'normal'::message_priority"))
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('direct', 'group', 'class', 'system', 'announcement', name='message_type', native_enum=False),
               type_=postgresql.ENUM('direct', 'group', 'class', 'system', 'announcement', name='message_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'direct'::message_type"))
    op.alter_column('message_recipients', 'recipient_type',
               existing_type=sa.Enum('user', 'group', 'class', name='recipient_type', native_enum=False),
               type_=postgresql.ENUM('user', 'class', 'role', name='recipient_type'),
               nullable=True,
               existing_server_default=sa.text("'user'::recipient_type"))
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.alter_column('chat_rooms', 'room_type',
               existing_type=sa.Enum('direct', 'group', 'class', 'system', 'announcement', name='message_type', native_enum=False),
               type_=postgresql.ENUM('direct', 'group', 'class', 'system', 'announcement', name='message_type'),
               existing_nullable=False)
    op.drop_column('chat_rooms', 'description')
    op.drop_column('chat_rooms', 'avatar_url')
    op.drop_column('chat_rooms', 'created_by')
    op.drop_index('ix_room_members_user', table_name='chat_room_members')
    op.drop_index('ix_room_members_room', table_name='chat_room_members')
    op.drop_table('chat_room_members')
    # ### end Alembic commands ###
