"""Add Notification

Revision ID: 9d4dc8e7a84a
Revises: ed8ba927bd71
Create Date: 2025-12-15 07:55:38.561572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d4dc8e7a84a'
down_revision: Union[str, None] = 'ed8ba927bd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_structure_sections', sa.Column('skill_area', sa.Enum('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', name='skill_area')))
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('schedule_change', 'assignment_due', 'grade_available', 'message_received', 'attendance_reminder', 'payment_due', 'system_alert', 'achievement', 'class_announcement', 'maintenance_notice', name='notification_type'),
               type_=sa.Enum('schedule_change', 'assignment_due', 'grade_available', 'attendance_reminder', 'class_announcement', 'message_received', 'achievement', 'payment_due', 'system_alert', 'maintenance_notice', name='notification_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notification_priority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', name='notification_priority', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'normal'::notification_priority"))
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_index('idx_notifications_expires', table_name='notifications')
    op.drop_index('idx_notifications_priority', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where='(read_at IS NULL)')
    op.alter_column('test_sections', 'skill_area',
               existing_type=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_sections', 'skill_area',
               existing_type=postgresql.ENUM('listening', 'reading', 'writing', 'speaking', 'grammar', 'vocabulary', 'pronunciation', name='skill_area'))
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'read_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_index('idx_notifications_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notifications_priority', 'notifications', ['priority'], unique=False)
    op.create_index('idx_notifications_expires', 'notifications', ['expires_at'], unique=False)
    op.create_index('idx_notifications_created', 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', name='notification_priority', native_enum=False),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', name='notification_priority'),
               nullable=True,
               existing_server_default=sa.text("'normal'::notification_priority"))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('schedule_change', 'assignment_due', 'grade_available', 'attendance_reminder', 'class_announcement', 'message_received', 'achievement', 'payment_due', 'system_alert', 'maintenance_notice', name='notification_type', native_enum=False),
               type_=postgresql.ENUM('schedule_change', 'assignment_due', 'grade_available', 'message_received', 'attendance_reminder', 'payment_due', 'system_alert', 'achievement', 'class_announcement', 'maintenance_notice', name='notification_type'),
               existing_nullable=False)
    op.drop_column('exam_structure_sections', 'skill_area')
    # ### end Alembic commands ###
