"""Message related adjustments

Revision ID: ba3439530cb9
Revises: 70e89c052097
Create Date: 2025-11-07 06:13:02.174935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba3439530cb9'
down_revision: Union[str, None] = '70e89c052097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('participant1_id', sa.UUID(), nullable=True),
    sa.Column('participant2_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant1_id', 'participant2_id', name='uq_direct_chat')
    )
    op.create_index('ix_chat_rooms_participants', 'chat_rooms', ['participant1_id', 'participant2_id'], unique=False)
    op.alter_column('file_uploads', 'upload_type',
               existing_type=postgresql.ENUM('avatar', 'document', 'audio', 'video', 'image', 'assignment', 'resource', name='upload_type'),
               type_=sa.Enum('avatar', 'document', 'audio', 'video', 'image', 'assignment', 'resource', name='user_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('file_uploads', 'processing_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processing_status'),
               type_=sa.Enum('pending', 'processing', 'completed', 'failed', name='user_status', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'pending'::processing_status"))
    op.alter_column('file_uploads', 'virus_scan_status',
               existing_type=postgresql.ENUM('pending', 'scanning', 'clean', 'infected', 'failed', name='scan_status'),
               type_=sa.Enum('pending', 'scanning', 'clean', 'infected', 'failed', name='user_status', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'pending'::scan_status"))
    op.alter_column('file_uploads', 'access_level',
               existing_type=postgresql.ENUM('private', 'class', 'public', 'restricted', name='access_level'),
               type_=sa.Enum('private', 'class', 'public', 'restricted', name='user_status', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'private'::access_level"))
    op.drop_index('idx_message_recipients_archived', table_name='message_recipients')
    op.drop_index('idx_message_recipients_recipient', table_name='message_recipients')
    op.drop_index('idx_message_recipients_unique', table_name='message_recipients')
    op.drop_index('idx_message_recipients_unread', table_name='message_recipients', postgresql_where='(read_at IS NULL)')
    op.drop_index('idx_message_recipients_unread_priority', table_name='message_recipients', postgresql_where='(read_at IS NULL)')
    op.create_index('ix_msg_recipient_unread', 'message_recipients', ['recipient_id', 'read_at'], unique=False)
    op.create_index('ix_msg_recipient_user', 'message_recipients', ['recipient_id', 'deleted'], unique=False)
    op.create_unique_constraint('uq_msg_recipient', 'message_recipients', ['message_id', 'recipient_id'])
    op.add_column('messages', sa.Column('chat_room_id', sa.UUID(), nullable=True))
    op.drop_index('idx_messages_created', table_name='messages')
    op.drop_index('idx_messages_scheduled', table_name='messages')
    op.drop_index('idx_messages_search', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('idx_messages_type', table_name='messages')
    op.create_index('ix_messages_chat_room_created', 'messages', ['chat_room_id', 'created_at'], unique=False)
    op.create_index('ix_messages_sender_created', 'messages', ['sender_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'messages', 'chat_rooms', ['chat_room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_messages_sender_created', table_name='messages')
    op.drop_index('ix_messages_chat_room_created', table_name='messages')
    op.create_index('idx_messages_type', 'messages', ['message_type'], unique=False)
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_search', 'messages', [sa.text("to_tsvector('english'::regconfig, (COALESCE(subject, ''::character varying)::text || ' '::text) || content)")], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_scheduled', 'messages', ['scheduled_at'], unique=False)
    op.create_index('idx_messages_created', 'messages', ['created_at'], unique=False)
    op.drop_column('messages', 'chat_room_id')
    op.drop_constraint('uq_msg_recipient', 'message_recipients', type_='unique')
    op.drop_index('ix_msg_recipient_user', table_name='message_recipients')
    op.drop_index('ix_msg_recipient_unread', table_name='message_recipients')
    op.create_index('idx_message_recipients_unread_priority', 'message_recipients', ['recipient_id', 'read_at', 'created_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_index('idx_message_recipients_unread', 'message_recipients', ['recipient_id', 'read_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_index('idx_message_recipients_unique', 'message_recipients', ['message_id', 'recipient_id'], unique=True)
    op.create_index('idx_message_recipients_recipient', 'message_recipients', ['recipient_id'], unique=False)
    op.create_index('idx_message_recipients_archived', 'message_recipients', ['recipient_id', 'archived'], unique=False)
    op.alter_column('file_uploads', 'access_level',
               existing_type=sa.Enum('private', 'class', 'public', 'restricted', name='user_status', native_enum=False),
               type_=postgresql.ENUM('private', 'class', 'public', 'restricted', name='access_level'),
               nullable=True,
               existing_server_default=sa.text("'private'::access_level"))
    op.alter_column('file_uploads', 'virus_scan_status',
               existing_type=sa.Enum('pending', 'scanning', 'clean', 'infected', 'failed', name='user_status', native_enum=False),
               type_=postgresql.ENUM('pending', 'scanning', 'clean', 'infected', 'failed', name='scan_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::scan_status"))
    op.alter_column('file_uploads', 'processing_status',
               existing_type=sa.Enum('pending', 'processing', 'completed', 'failed', name='user_status', native_enum=False),
               type_=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processing_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::processing_status"))
    op.alter_column('file_uploads', 'upload_type',
               existing_type=sa.Enum('avatar', 'document', 'audio', 'video', 'image', 'assignment', 'resource', name='user_status', native_enum=False),
               type_=postgresql.ENUM('avatar', 'document', 'audio', 'video', 'image', 'assignment', 'resource', name='upload_type'),
               existing_nullable=False)
    op.drop_index('ix_chat_rooms_participants', table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
