"""Message service update

Revision ID: bd7695eec92f
Revises: 5fc00f03d124
Create Date: 2025-12-27 23:40:44.777445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd7695eec92f'
down_revision: Union[str, None] = '5fc00f03d124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_rooms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_rooms', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_rooms', 'users', ['updated_by'], ['id'])
    op.alter_column('question_groups', 'question_type',
               existing_type=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               nullable=False)
    op.create_unique_constraint(None, 'question_groups', ['part_id', 'order_number'])
    op.alter_column('test_responses', 'auto_graded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_responses', 'auto_graded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'question_groups', type_='unique')
    op.alter_column('question_groups', 'question_type',
               existing_type=postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', 'essay', 'listening', 'speaking', 'reading_comprehension', 'fill_in_blank', 'matching', 'ordering', 'drag_and_drop', name='question_type'),
               nullable=True)
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_column('chat_rooms', 'updated_by')
    op.drop_column('chat_rooms', 'deleted_at')
    op.drop_column('chat_rooms', 'updated_at')
    # ### end Alembic commands ###
