"""add_class_id_to_flashcard_decks

Revision ID: db547f644f41
Revises: 540f37ea3a1a
Create Date: 2026-09-22 12:00:25.082956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db547f644f41'
down_revision: Union[str, None] = '540f37ea3a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard_decks', sa.Column('class_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'flashcard_decks', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcard_decks', type_='foreignkey')
    op.drop_column('flashcard_decks', 'class_id')
    # ### end Alembic commands ###
