"""add finance tables

Revision ID: e9f93078cf92
Revises: f1a2b3c4d5e6
Create Date: 2026-04-27 21:19:24.993547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f93078cf92'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ga_runs.status: VARCHAR -> native enum
    # Must drop default first, then alter type, then re-set default
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ga_run_status') THEN CREATE TYPE ga_run_status AS ENUM ('pending', 'running', 'completed', 'failed', 'applied'); END IF; END $$")
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status TYPE ga_run_status USING status::ga_run_status")
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status SET DEFAULT 'pending'::ga_run_status")
    op.drop_index('ix_ga_runs_status', table_name='ga_runs')
    op.drop_index('ix_ga_schedule_proposals_session_date', table_name='ga_schedule_proposals')
    op.alter_column('kpi_approval_logs', 'action',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'REQUEST_REVISION', name='kpi_approval_action', native_enum=False),
               existing_nullable=False)
    op.alter_column('kpi_metric_results', 'data_source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MANUAL', 'AUTO_SYNC', 'CALCULATED', name='kpi_data_source', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'''MANUAL'''::character varying"))
    op.alter_column('kpi_periods', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SEMESTER', 'MONTHLY', 'QUARTERLY', name='kpi_period_type', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'''SEMESTER'''::character varying"))
    op.alter_column('kpi_records', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='kpi_approval_status', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'''DRAFT'''::character varying"))
    op.alter_column('kpi_template_metrics', 'unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PERCENT', 'SCORE', 'COUNT', 'STUDENT', name='kpi_metric_unit', native_enum=False),
               existing_nullable=True)
    op.alter_column('kpi_templates', 'contract_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FULL_TIME', 'PART_TIME', 'NATIVE', name='kpi_template_contract_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('kpi_templates', 'bonus_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FIXED_PER_PERIOD', 'PER_HOUR', name='kpi_template_bonus_type', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'''FIXED_PER_PERIOD'''::character varying"))
    op.drop_index('ix_teacher_unavailability_date', table_name='teacher_unavailability')
    # tests.test_type: skip alter — column is already VARCHAR(20) and works fine
    # Alembic auto-gen tries to shrink to VARCHAR(10) which truncates existing data
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # tests.test_type: skipped (no-op, see upgrade)

    op.create_index('ix_teacher_unavailability_date', 'teacher_unavailability', ['unavailable_date'], unique=False)
    op.alter_column('kpi_templates', 'bonus_type',
               existing_type=sa.Enum('FIXED_PER_PERIOD', 'PER_HOUR', name='kpi_template_bonus_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'''FIXED_PER_PERIOD'''::character varying"))
    op.alter_column('kpi_templates', 'contract_type',
               existing_type=sa.Enum('FULL_TIME', 'PART_TIME', 'NATIVE', name='kpi_template_contract_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('kpi_template_metrics', 'unit',
               existing_type=sa.Enum('PERCENT', 'SCORE', 'COUNT', 'STUDENT', name='kpi_metric_unit', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('kpi_records', 'approval_status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='kpi_approval_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'''DRAFT'''::character varying"))
    op.alter_column('kpi_periods', 'period_type',
               existing_type=sa.Enum('SEMESTER', 'MONTHLY', 'QUARTERLY', name='kpi_period_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'''SEMESTER'''::character varying"))
    op.alter_column('kpi_metric_results', 'data_source',
               existing_type=sa.Enum('MANUAL', 'AUTO_SYNC', 'CALCULATED', name='kpi_data_source', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'''MANUAL'''::character varying"))
    op.alter_column('kpi_approval_logs', 'action',
               existing_type=sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'REQUEST_REVISION', name='kpi_approval_action', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index('ix_ga_schedule_proposals_session_date', 'ga_schedule_proposals', ['session_date'], unique=False)
    op.create_index('ix_ga_runs_status', 'ga_runs', ['status'], unique=False)
    # ga_runs.status: native enum -> VARCHAR
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status TYPE VARCHAR(20) USING status::text")
    op.execute("ALTER TABLE ga_runs ALTER COLUMN status SET DEFAULT 'pending'")
    op.execute("DROP TYPE IF EXISTS ga_run_status")
    # ### end Alembic commands ###
