"""Refactor test-exam models

Revision ID: ed8ba927bd71
Revises: 8cb13ac9bcda
Create Date: 2025-12-03 23:10:09.854066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed8ba927bd71'
down_revision: Union[str, None] = '8cb13ac9bcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exam_structures',
    sa.Column('exam_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_structure_sections',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('order_number > 0', name='check_structure_section_order_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['exam_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'order_number', name='uq_structure_section_order')
    )
    op.create_table('exam_structure_parts',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('min_questions', sa.Integer(), nullable=True),
    sa.Column('max_questions', sa.Integer(), nullable=True),
    sa.Column('question_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('order_number > 0', name='check_structure_part_order_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['exam_structure_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'order_number', name='uq_structure_part_order')
    )
    op.create_table('test_sections',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('structure_section_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('order_number > 0', name='check_test_section_order_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['structure_section_id'], ['exam_structure_sections.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'order_number', name='uq_test_section_order')
    )
    op.create_table('test_section_parts',
    sa.Column('test_section_id', sa.UUID(), nullable=False),
    sa.Column('structure_part_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('min_questions', sa.Integer(), nullable=True),
    sa.Column('max_questions', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('order_number > 0', name='check_test_section_part_order_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['structure_part_id'], ['exam_structure_parts.id'], ),
    sa.ForeignKeyConstraint(['test_section_id'], ['test_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_section_id', 'order_number', name='uq_test_section_part_order')
    )
    op.add_column('question_bank', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('question_bank', 'difficulty_level',
               existing_type=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               nullable=True)
    op.alter_column('question_bank', 'audio_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_bank', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_bank', 'points',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('1.00'))
    op.execute("""
    ALTER TABLE question_bank
    ALTER COLUMN tags
    TYPE JSONB
    USING to_jsonb(tags);
""")
    op.alter_column('question_bank', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('question_bank', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::content_status"))
    op.drop_column('question_bank', 'course_level')
    op.drop_column('question_bank', 'time_limit_seconds')
    op.alter_column('test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_attempts', 'status',
               existing_type=postgresql.ENUM('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status'),
               nullable=False,
               existing_server_default=sa.text("'in_progress'::attempt_status"))
    op.execute("""
    ALTER TABLE test_attempts
    ALTER COLUMN ip_address
    TYPE INET
    USING ip_address::inet;
""")
    op.drop_constraint('uq_test_student_attempt', 'test_attempts', type_='unique')
    op.create_unique_constraint('uq_attempt_unique', 'test_attempts', ['test_id', 'student_id', 'attempt_number'])
    op.add_column('test_questions', sa.Column('part_id', sa.UUID(), nullable=True))
    op.alter_column('test_questions', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('uq_test_question', 'test_questions', type_='unique')
    op.create_unique_constraint('uq_test_question_order', 'test_questions', ['test_id', 'order_number'])
    op.create_unique_constraint('uq_test_question_unique', 'test_questions', ['test_id', 'question_id'])
    op.create_foreign_key(None, 'test_questions', 'test_section_parts', ['part_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_responses', 'audio_response_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('test_responses', 'points_earned',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_responses', 'flagged_for_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_response_attempt_question', 'test_responses', ['attempt_id', 'question_id'])
    op.add_column('tests', sa.Column('exam_type_id', sa.UUID(), nullable=True))
    op.add_column('tests', sa.Column('structure_id', sa.UUID(), nullable=True))
    op.alter_column('tests', 'total_points',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tests', 'passing_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('tests', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tests', 'randomize_questions',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tests', 'show_results_immediately',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tests', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'active', 'closed', 'archived', name='test_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::test_status"))
    op.alter_column('tests', 'ai_grading_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tests', 'test_type',
               existing_type=postgresql.ENUM('quiz', 'midterm', 'final', 'placement', 'ielts_full', 'ielts_practice', 'homework', 'assessment', name='test_type'),
               nullable=True)
    op.create_foreign_key(None, 'tests', 'exam_types', ['exam_type_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'exam_structures', ['structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.alter_column('tests', 'test_type',
               existing_type=postgresql.ENUM('quiz', 'midterm', 'final', 'placement', 'ielts_full', 'ielts_practice', 'homework', 'assessment', name='test_type'),
               nullable=False)
    op.alter_column('tests', 'ai_grading_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tests', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'active', 'closed', 'archived', name='test_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::test_status"))
    op.alter_column('tests', 'show_results_immediately',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tests', 'randomize_questions',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tests', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('tests', 'passing_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('tests', 'total_points',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('tests', 'structure_id')
    op.drop_column('tests', 'exam_type_id')
    op.drop_constraint('uq_response_attempt_question', 'test_responses', type_='unique')
    op.alter_column('test_responses', 'flagged_for_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('test_responses', 'points_earned',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('test_responses', 'audio_response_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_constraint('uq_test_question_unique', 'test_questions', type_='unique')
    op.drop_constraint('uq_test_question_order', 'test_questions', type_='unique')
    op.create_unique_constraint('uq_test_question', 'test_questions', ['test_id', 'question_id'])
    op.alter_column('test_questions', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('test_questions', 'part_id')
    op.drop_constraint('uq_attempt_unique', 'test_attempts', type_='unique')
    op.create_unique_constraint('uq_test_student_attempt', 'test_attempts', ['test_id', 'student_id', 'attempt_number'])
    op.execute("""
    ALTER TABLE test_attempts
    ALTER COLUMN ip_address
    TYPE INET
    USING ip_address::inet;
""")
    op.alter_column('test_attempts', 'status',
               existing_type=postgresql.ENUM('in_progress', 'submitted', 'graded', 'cancelled', 'expired', name='attempt_status'),
               nullable=True,
               existing_server_default=sa.text("'in_progress'::attempt_status"))
    op.alter_column('test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('question_bank', sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('question_bank', sa.Column('course_level', postgresql.ENUM('beginner', 'elementary', 'intermediate', 'upper_intermediate', 'advanced', 'proficiency', name='course_level'), autoincrement=False, nullable=False))
    op.alter_column('question_bank', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'inactive', 'archived', 'under_review', name='content_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::content_status"))
    op.alter_column('question_bank', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.execute("""
    ALTER TABLE question_bank
    ALTER COLUMN tags
    TYPE JSONB
    USING to_jsonb(tags);
""")
    op.alter_column('question_bank', 'points',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('1.00'))
    op.alter_column('question_bank', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_bank', 'audio_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_bank', 'difficulty_level',
               existing_type=postgresql.ENUM('very_easy', 'easy', 'medium', 'hard', 'very_hard', name='difficulty_level'),
               nullable=False)
    op.drop_column('question_bank', 'extra_metadata')
    op.drop_table('test_section_parts')
    op.drop_table('test_sections')
    op.drop_table('exam_structure_parts')
    op.drop_table('exam_structure_sections')
    op.drop_table('exam_structures')
    op.drop_table('exam_types')
    # ### end Alembic commands ###
