"""add recommendation_logs

Revision ID: f042960a32f9
Revises: b1c2d3e4f5g6
Create Date: 2026-05-10 22:11:34.260323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f042960a32f9'
down_revision: Union[str, None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_logs',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attendance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_band', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('target_cefr', sa.String(length=5), nullable=True),
    sa.Column('predicted_band', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('predicted_cefr', sa.String(length=5), nullable=True),
    sa.Column('weakest_skill', sa.String(length=50), nullable=True),
    sa.Column('estimated_weeks', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('recommendation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('recommendation_logs')
    # ### end Alembic commands ###
