name: Daily Recommendation
on:
  schedule:
    - cron: "0 23 * * *" # 6 AM UTC+7 = 23:00 UTC
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Batch Recommendation
        run: |
          curl -X POST "${{ secrets.BE_URL }}/api/v1/recommendations/generate-batch" \
            -H "Authorization: Bearer ${{ secrets.CRON_TOKEN }}"
